app/iform/urls.py
from django.conf.urls import url

from app.iform.views import IFormList, iform_update, IFormDelete, iform_create

urlpatterns = [
    url(r'^create$', iform_create, name='iform_create'),
    url(r'^list$', IFormList.as_view(), name='iform_list'),
    url(r'^update/(?P<pk>[0-9A-Za-z-]+)/$', iform_update, name='iform_update'),
    url(r'^delete/(?P<pk>[0-9A-Za-z-]+)/$', IFormDelete.as_view(), name='iform_delete'),

]

app/inspection/urls.py
from django.conf.urls import url

from app.inspection.views import InspectionList, InspectionDelete
from app.inspection.views import inspection_create, inspection_update, get_data_collections #, inspection_data_collections
urlpatterns = [
    url(r'^list$', InspectionList.as_view(), name='inspection_list'),

    url(r'^values/(?P<iform_pk>[0-9A-Za-z-]+)/$', get_data_collections, name='inspection_values'),

    url(r'^delete/(?P<pk>\d+)/$', InspectionDelete.as_view(), name='inspection_delete'),

    # This pattern is passing the UUID from the iform we want to create the inspection from.
    url(r'^create/(?P<pk>[0-9A-Za-z-]+)/$', inspection_create, name='inspection_create'),

    # These patterns are passing the inspection ID itself.
    url(r'^update/(?P<pk>\d+)/$', inspection_update, name='inspection_update'),

]

app/tag/urls.py
from django.conf.urls import url

from app.tag.views import TagCreate, TagList, TagUpdate, TagDelete

urlpatterns = (
    url(r'^create$', TagCreate.as_view(), name='tag_create'),
    url(r'^list$', TagList.as_view(), name='tag_list'),
    url(r'^update/(?P<pk>[0-9A-Za-z-]+)/$', TagUpdate.as_view(), name='tag_update'),
    url(r'^delete/(?P<pk>[0-9A-Za-z-]+)/$', TagDelete.as_view(), name='tag_delete'),

)

icontrol/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static


urlpatterns = [
        url(r'^$', RedirectView.as_view(url='iform/list')),
        url(r'^tag/', include(('app.tag.urls', 'tag'), namespace='tag')),
        url(r'^iform/', include(('app.iform.urls', 'iform'), namespace='iform')),
        url(r'^inspection/', include(('app.inspection.urls', 'inspection'), namespace='inspection')),
        url(r'^chart/', include(('app.chart.urls', 'chart'), namespace='chart')),
        url(r'^admin/', admin.site.urls),
        url(r'^accounts/', include('django.contrib.auth.urls')),
]

icontrol/models.py
# -*- coding: utf-8 -*-

from django.db.models import ForeignKey, DateTimeField, BooleanField
from django.db import models
from django.contrib.auth.models import User
import datetime

class ControlModel(models.Model):

    class Meta:
        abstract = True
    # thanks to https://stackoverflow.com/questions/42899817
    @staticmethod
    def get_related_name():
        return '%(app_label)s_%(class)s'

    created_by = ForeignKey(User, null=True, blank=True,related_name="created"+get_related_name.__func__()
                            , on_delete=models.CASCADE)
    updated_by = ForeignKey(User, null=True, blank=True, related_name="updated"+get_related_name.__func__()
                            , on_delete=models.CASCADE)
    created_when = DateTimeField(auto_now_add=True)
    updated_when = DateTimeField(auto_now=True)
    is_active = BooleanField(default=True)

icontrol/templates/base/base.html
{% load static %}

{# Load the tag library #}
{% load bootstrap3 %}
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<html lang="pt-bt">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<title>{% block title %}Inventsis{% endblock %}</title>
</head>
<body>
 <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'iform:iform_list' %}">Enterprise Data Repository</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" 
              aria-expanded="false">List <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li><a href="{% url 'tag:tag_list' %}">Tags</a></li>
                  <li><a href="{% url 'iform:iform_list' %}">Forms</a></li>
                  <li><a href="{% url 'inspection:inspection_list' %}">Inspections</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" 
              aria-expanded="false">Create <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li><a href="{% url 'tag:tag_create' %}">Tags</a></li>
                  <li><a href="{% url 'iform:iform_create' %}">Forms</a></li>
                  <li role="separator" class="divider"></li>
                  <!--<li class="dropdown-header">Nav header</li>-->
                  <!--<li><a href="#">Separated link</a></li>-->
                  <!--<li><a href="#">One more separated link</a></li>-->
              </ul>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" 
              aria-expanded="false">Status<span class="caret"></span></a>
              <ul class="dropdown-menu">
                  {% if user.is_authenticated %}
                    <li class="navbar-text">Logged as
                        {{ user.get_username }}
                    </li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
                  {% else %}
                    <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
                  {% endif %} 
              
                  <li><a href="#">Settings</a></li>
              </ul>
            </li>
                  <li><a href="{% url 'iform:iform_list' %}">Home</a></li>
                  <li><a href="mailto:rogerio@inventsis.com.br">Contact</a></li>
                 
              </li>
          </ul>
        </div>
      </div>
    </nav>


        <div class="container">
	{% block content %}
	<h4> Invent sistemas </h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
</div>

	{% block extrajs %}
	{% endblock %}


</body>
</html>